kind: SwitchConfig
version: v1alpha1
kubeconfigStores:
  - kind: filesystem
    paths:
      - ~/tmp/.kube.config
      - ~/devel/piontec-github/oci-infra/tf/.kube.config
      - ~/devel/piontec-github/oci-test/tf/.kube.config
